# Generated by Django 3.1 on 2020-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('team_name', models.CharField(max_length=200)),
                ('wiki_link', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('track', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('parts_link', models.URLField()),
                ('medal', models.CharField(max_length=200)),
                ('nomination', models.CharField(max_length=200)),
                ('award', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('year', 'region', 'location', 'institution'),
            },
        ),
    ]
